export const SERVICE_NAME = {
  SAP_CONSULTING_SESSION: 'SAP_CONSULTING_SESSION',
  FINANCIAL_AUDIT: 'FINANCIAL_AUDIT',
  SAP_SYSTEM_OPTIMIZATION: 'SAP_SYSTEM_OPTIMIZATION',
  PROCESS_AUTOMATION: 'PROCESS_AUTOMATION',
} as const;

export type ServiceName = (typeof SERVICE_NAME)[keyof typeof SERVICE_NAME];

export const SERVICE_NAME_VALUES: ServiceName[] = Object.values(SERVICE_NAME);
